### ISSUE TITLE
custom operator validation not working

### ISSUE THREAD

**Issue by jman057** [KennethanCeyer/Formula#1]
Hi, just trying the demo and noticed that the custom operator doesn't seem to be recognised as valid even when put in the correct place, e.g., between two values. When I call getFormula() it seems to lack a unit.

**Comment by KennethanCeyer** [comment]
Hi @jman057,

First of all thank you for asking me.

I think you need to add ```data-value``` attribute at your "unit" element.

even though if you get same problem, please ask me again with codepen sample.

**Comment by KennethanCeyer** [comment]
I am understand what is the problem @jman057.

"custom operator(+)" is just custom variable name, It means that parser is noticed it as variable.

I think you need "real custom operator".

This feature not added yet (i'll try to make this feature soon).

By the way, if you need formula data more detail than getFormula(), you can use as below.

```javascript
$formula.data('formula').getFormula(function(data) {
	// data.data is formula parsed object data.
	console.log(data.data);
 });
```
